### ISSUE TITLE
HostAndPort.getHostTest() has been deprecated in favor of getHost() in Guava 20.0

### ISSUE THREAD

**Issue by mattnathan** [rickfast/consul-client#214]
While this isn't an issue until Guava 22.0, when the method will be removed, I thought I'd create an issue anyway just to track it.

See https://github.com/google/guava/wiki/Release20#commonnet

**Comment by aiyanbo** [comment]
+1

**Comment by adericbourg** [comment]
It seems like this issue can be closed since it's been fixed by https://github.com/OrbitzWorldwide/consul-client/commit/17d06548d3d19a6db5e3d044744f69b3a7e8fe24 (#254)
