### ISSUE TITLE
KeyValueClient.getKeys throws 404 instead of empty list when the path does not exist

### ISSUE THREAD

**Issue by asador** [rickfast/consul-client#225]
If the given key does not exist, calling getKeys on it never returns an empty list, instead it throws ConsulException with 404 code, while getValue method doesn't throw 404 in the same scenario. These methods should be consistent in handling key not found situation.

**Comment by YannRobert** [comment]
looks like #173

**Comment by akd31** [comment]
(https://github.com/OrbitzWorldwide/consul-client/blob/67a64b9f2331ae4ea88fdab2ace16f48064c0e64/src/main/java/com/orbitz/consul/KeyValueClient.java#L357 )


says @return A list of zero to many keys. However it throws Consul Exception when the path doesn't exist. I think it should return empty list either.

**Comment by yfouquet** [comment]
Hi guys,

I cannot reproduce your issue with the current version (which i admit has evolved since your issue was created. Calling `getValue` with non existing path returns an `Optional.empty()`.
```
Optional<Value> value = kvClient.getValue("non-existing-path");
Assert.assertFalse(value.isPresent()); //works fine
```
If you still encounter the issue, feel free to reopen the issue.

**Comment by hansenc** [comment]
@yfouquet this happens with `getKeys` and not with `getValue` or `getValues`.  This happens for me with version 1.4.0 (current latest).
```java
List<String> keys = kvClient.getKeys("non-existing-path"); //throws ConsulException
```
Stacktrace:
```
com.orbitz.consul.ConsulException: Consul request failed with status [404]: 

	at com.orbitz.consul.util.Http.ensureResponseSuccessful(Http.java:61)
	at com.orbitz.consul.util.Http.extract(Http.java:33)
	at com.orbitz.consul.KeyValueClient.getKeys(KeyValueClient.java:476)
	at com.orbitz.consul.KeyValueClient.getKeys(KeyValueClient.java:460)
```
