### ISSUE TITLE
enforcer.DependencyConvergence failed

### ISSUE THREAD

**Issue by sverhagen** [rickfast/consul-client#234]
Using 0.14.0.

Getting a [dependency convergence failure](http://maven.apache.org/enforcer/enforcer-rules/dependencyConvergence.html), using the Maven Enforcer Plugin. Through two different dependency paths, this library depends on two different versions of `com.squareup.retrofit2:retrofit`. This is not highly critical, and things likely work for most people (they did "work" fine for me), but the Enforcer isn't wrong either, and it should probably be an easy fix also. For people using the Enforcer, they will have to add `dependencyManagement` to pin the right version of `retrofit`, which is a maintenance hazard.

    [INFO] --- maven-enforcer-plugin:1.3.1:enforce (enforce) @ project-id ---
    [WARNING]
    Dependency convergence error for com.squareup.retrofit2:retrofit:2.1.0 paths to dependency are:
    +-com.organization:project-id:1.0.4-SNAPSHOT
      +-com.orbitz.consul:consul-client:0.14.0
        +-com.squareup.retrofit2:retrofit:2.1.0
    and
    +-com.organization:project-id:1.0.4-SNAPSHOT
      +-com.orbitz.consul:consul-client:0.14.0
        +-com.squareup.retrofit2:converter-jackson:2.0.2
          +-com.squareup.retrofit2:retrofit:2.0.2
    
    [WARNING] Rule 1: org.apache.maven.plugins.enforcer.DependencyConvergence failed with message:
    Failed while enforcing releasability the error(s) are [
    Dependency convergence error for com.squareup.retrofit2:retrofit:2.1.0 paths to dependency are:
    +-com.organization:project-id:1.0.4-SNAPSHOT
      +-com.orbitz.consul:consul-client:0.14.0
        +-com.squareup.retrofit2:retrofit:2.1.0
    and
    +-com.organization:project-id:1.0.4-SNAPSHOT
      +-com.orbitz.consul:consul-client:0.14.0
        +-com.squareup.retrofit2:converter-jackson:2.0.2
          +-com.squareup.retrofit2:retrofit:2.0.2

**Comment by yfouquet** [comment]
Hi @sverhagen,
It has been fixed in 1.0.1 (see [57a7462](https://github.com/rickfast/consul-client/commit/57a74626f4ed7a42d26cbcea034681e00f92050f)).
Thanks for the notice.
