### ISSUE TITLE
Value.getValueAsString Charset error

### ISSUE THREAD

**Issue by shortstories** [rickfast/consul-client#257]
Because of using Korean windows, my java default charset is `MS949`. In this case, I get broken result when I call `Value.getValueAsString()` for get value that contains korean. It is natural result because consul uses `UTF-8` to convert string to bytes. Perhaps a similar problem can occur in Chinese and Japanese.

To solve this problem, there are the following methods.
1. Add JVM Option : `-Dfile.encoding=UTF-8`
2. Manual decoding : `new String(BaseEncoding.base64().decode(value.getValue().get()), Charset.forName("UTF-8"));`

However, There are easy to forget and troublesome.
I think it is better to put a `UTF-8` charset explicitly in `new String ()`. Otherwise, It would be better provide an option to specify the consul client default charset. At least, please overload `getValueAsString` to be able to choice another charset.

**Comment by rickfast** [comment]
Make a PR and I'll merge it. Otherwise, I won't be able to get to this until next week

**Comment by yfouquet** [comment]
Hi @shortstories ,

A fix to your issue has been merged in 1.0.1 (see [29cb189).](https://github.com/rickfast/consul-client/commit/29cb189d86c061c37df5256b350cbf1d1ce5ea79)
A method is available to specify the Charset: `KeyValueClient#getValueAsString(String, Charset)`
