### ISSUE TITLE
byte array support for kV value.

### ISSUE THREAD

**Issue by shekhar2709** [rickfast/consul-client#275]
I need an api help to store byte[] in kV, as we can do in zookeeper. I am using consul-client java api's. Please help

**Comment by shekhar2709** [comment]
I digged into the api code and found that string is ultimately converted to byte[], which is quite obvious. But consul-client api is not exposing any api to take byte[] as KV value input. Please provide such an api, it should not be a difficult affair.

Code reference :
Class - okhttp3.RequestBody

public static RequestBody create(@Nullable MediaType contentType, String content) {
    Charset charset = Util.UTF_8;
    if (contentType != null) {
      charset = contentType.charset();
      if (charset == null) {
        charset = Util.UTF_8;
        contentType = MediaType.parse(contentType + "; charset=utf-8");
      }
    }
    byte[] bytes = content.getBytes(charset);
    return create(contentType, bytes);
  }

**Comment by shekhar2709** [comment]
@rickfast We would need change into 
1. com.orbitz.okhttp3.jar - okhttp3.RequestBody.java
2. com.orbitz.consul.KeyValueClient.java

**Comment by rickfast** [comment]
Can’t you just create a string from your byte array e.g. `new String(myByteArray)`?

**Comment by shekhar2709** [comment]
Thanks for your suggestion. I did not realize that we could actually recreated my serialized object by this. I will try out.

**Comment by shekhar2709** [comment]
Not able to deserialize my Object. 
Getting java.io.StreamCorruptedException: invalid stream header: 77717A44


Here is part of my test code.

MyInvokePacket packet = new MyInvokePacket();
kvClient.putValue("k1", new String(serialize(packet)));			
Optional<Value> op = kvClient.getValue("k1");
Value v = op.get();
Optional<String> ss= v.getValue();
String s2 = ss.get();
Object deser = deserialize(s2.getBytes());



public static byte[] serialize(Object object) {
		try{
			ByteArrayOutputStream bos = new ByteArrayOutputStream();
			ObjectOutput out = new ObjectOutputStream(bos);
			out.writeObject(object);
	        return bos.toByteArray();
		}catch(IOException ioe){
			return null;
		}
	}
	
	
	public static Object deserialize(byte[] data) {
		try{
			ByteArrayInputStream bis = new ByteArrayInputStream(data);
			ObjectInput in = new ObjectInputStream(bis);
			Object o = in.readObject();
			return o;
		}catch(IOException ioe){
			return null;
		} catch (ClassNotFoundException e) {
			e.printStackTrace();
			return null;
		}
	}

**Comment by shekhar2709** [comment]
@rickfast Please see above code. I cannot recreate my object.
Ecwid/consul-api provides - getKVBinaryValue("somekey") api for the same purpose. This does perfect job.

**Comment by rickfast** [comment]
Ok then you can either use that other library or make a pull request. It is unlikely that I will have time to implement this for you in the near future

**Comment by rkx-bloodshed** [comment]
add in https://github.com/rickfast/consul-client/pull/310

**Comment by yfouquet** [comment]
I guess the issue can now be closed, as byte array are now supported.
