### ISSUE TITLE
Improving the library

### ISSUE THREAD

**Issue by yfouquet** [rickfast/consul-client#294]
Hello @rickfast,

We are using this library at scale for more than a year now.
We would like to keep improving the library, mostly regarding monitoring and tests.

I have pushed some PRs, but many others are to come. Would you consider discussing the possibility to give me or one of my teammates push rights on the library? As you can see on the previous PR, we will take care on not braking the library and not changing its public API.

Best,
Yoann.

**Comment by rickfast** [comment]
This repo is managed by Orbitz/Expedia.com and only employees have access for push. I'm out of the country for work at the moment, but I can talk to our security group at Expedia to find out if its appropriate to give non-employees push access. Will let you know.

**Comment by yfouquet** [comment]
Noted, thanks.

**Comment by rickfast** [comment]
I’m going to see if I can transfer the repo to `/rickfast`, at which point I can give you push access. Will let you know.

**Comment by yfouquet** [comment]
Awesome, do you want me to stop pushing PR until its done?
Or

**Comment by rickfast** [comment]
no. i still have to get approval to transfer the repository, but I don't expect it to be an issue considering I'm the only employee contributing

**Comment by rickfast** [comment]
any PRs on this repo will be transferred anyway

**Comment by yfouquet** [comment]
(sorry for the closing issue)
That's good for us, thanks @rickfast.

**Comment by rickfast** [comment]
you and alban are now contributors. enjoy! i will still have to perform releases for the time being

**Comment by yfouquet** [comment]
Thanks a lot @rickfast!!
