### ISSUE TITLE
CHANGELOG and Releases have diverged

### ISSUE THREAD

**Issue by cricket007** [rickfast/consul-client#305]
Please update your CHANGELOG when you release a new version.

**Comment by rickfast** [comment]
I’ll rmember that next time.

**Comment by cricket007** [comment]
Any plans to go back over and fill in the missing versions? Reason being - we have some legacy apps that are using an older version of Guava, and want to more easily know which version to pick

**Comment by rickfast** [comment]
The next time I generate it it should create a change entry for all Missed changes

**Comment by rickfast** [comment]
https://github.com/rickfast/consul-client/blob/master/CHANGELOG.md

**Comment by cricket007** [comment]
bump @rickfast
