### ISSUE TITLE
Unable to shut down immediately during a blocking query

### ISSUE THREAD

**Issue by ZstringX** [rickfast/consul-client#307]
Consul consul = Consul.builder()
            .withReadTimeoutMillis(5 * 60 * 1000)
            .build();
    
    Thread t = new Thread(() -> {
        Optional<Value> v = consul.keyValueClient().getValue("key");
        BigInteger index = BigInteger.valueOf(v.get().getModifyIndex());
        QueryOptions options = ImmutableQueryOptions.builder()
                .index(index)
                .wait("1m")
                .build();
        System.out.println("before blocking");
        try {
            consul.keyValueClient().getValue("key", options);
        } catch (ConsulException e) {
            // ignore
        }
        System.out.println("after blocking");
    });
    t.start();
    
    try {
        Thread.sleep(1000);
        consul.destroy();           // not working
        t.interrupt();              // also not working
        t.join();                   // will block until the blocking query ends
    } catch (Exception e) {
        e.printStackTrace();
    }

The thread will be blocking on socket.read()
Maybe the socket should be manually closed when calling consul.destroy()?

**Comment by ZstringX** [comment]
this should do the trick #308

**Comment by yfouquet** [comment]
I've checked and it also works for caches.
Thanks @ZstringX.
