### ISSUE TITLE
support service meta-data

### ISSUE THREAD

**Issue by chenjpu** [rickfast/consul-client#321]
See [hashicorp/consul#3881](https://github.com/hashicorp/consul/pull/3881) -> [hashicorp/consul#1107](https://github.com/hashicorp/consul/issues/1107) .

**Comment by yfouquet** [comment]
Hi @chenjpu,
This feature was release on April 13th in consul 1.0.7.
Hence, we need to upgrade the version of consul first (and ensure compatibility), and then add support for service meta-data.
