### ISSUE TITLE
Cannot build TaggedAddresses, some of required attributes are not set [lan]

### ISSUE THREAD

**Issue by wang-shuai** [rickfast/consul-client#329]
` healthClient.getServiceChecks `  return healthy info
but when debug  ` healthClient.getHealthyServiceInstances ` 
the program builds url like 'http://localhost:8500/v1/health/service/esgrpc'
view in the brower，return info like：
``` json
[{
		"Node" : {
			"Node" : "ESWeb",
			"Address" : "192.168.156.247",
			"TaggedAddresses" : {
				"wan" : "192.168.156.247"
			},
			"CreateIndex" : 32198,
			"ModifyIndex" : 10790017
		},
		"Service" : {
			"ID" : "esgrpc",
			"Service" : "esgrpc",
			"Tags" : ["grpc", "main"],
			"Address" : "",
			"Port" : 50021,
			"EnableTagOverride" : false,
			"CreateIndex" : 32206,
			"ModifyIndex" : 10539320
		},
		"Checks" : [{
				"Node" : "ESWeb",
				"CheckID" : "serfHealth",
				"Name" : "Serf Health Status",
				"Status" : "passing",
				"Notes" : "",
				"Output" : "Agent alive and reachable",
				"ServiceID" : "",
				"ServiceName" : "",
				"CreateIndex" : 32198,
				"ModifyIndex" : 10790004
			}, {
				"Node" : "ESWeb",
				"CheckID" : "service:esgrpc",
				"Name" : "Service 'esgrpc' check",
				"Status" : "passing",
				"Notes" : "",
				"Output" : "TCP connect 192.168.156.247:50021: Success",
				"ServiceID" : "esgrpc",
				"ServiceName" : "esgrpc",
				"CreateIndex" : 32206,
				"ModifyIndex" : 10539320
			}
		]
	}
]
```
` healthClient.getHealthyServiceInstances `  throw exception info like follows
> com.fasterxml.jackson.databind.exc.InvalidDefinitionException: Cannot construct instance of `com.orbitz.consul.model.catalog.ImmutableTaggedAddresses`, problem: Cannot build TaggedAddresses, some of required attributes are not set [lan]

**Comment by yfouquet** [comment]
Hi @wang-shuai ,
Which version of Consul are use using?
Looking at the consul agent code, the "lan" address was added in Consul 0.7.

**Comment by zz85** [comment]
I'm facing this problem with Consul 0.6 too. Can https://github.com/rickfast/consul-client/blob/master/src/main/java/com/orbitz/consul/model/catalog/TaggedAddresses.java#L20

be changed to 
```java
public abstract Optional<String> getLan();
```

to fix this?

**Comment by yfouquet** [comment]
Making it optional will have no impact on recent version of Consul. So, let's make it available.
