### ISSUE TITLE
Register Check do not work if not TTL

### ISSUE THREAD

**Issue by sliabat** [rickfast/consul-client#340]
Hi,

I try to register a check with a script, and it dos not work. It seams your code has the deprecated API of check register.

This is the json who work : www.www.fr//v1/agent/check/register
`{
  "ID": "ws-devops-js",
  "Name": "ws-devops-js",
"ServiceID": "ws-devops-js",
"args": ["/opt/devops/scripts/consul/check_cassiopee_to_consul.sh", "http://devops.ucanss.fr:5001/supervision"],
  "Interval": "15s",
  "TLSSkipVerify": true,
	"timeout":"10s",
	"DeregisterCriticalServiceAfter": "90m"
}`

As you can see, the Consul API is now `args` with an array. First is the script, others elements are parameters.

This is the code of your api, who did not working : 
```
Check check = ImmutableCheck.builder()
					.id(appNAme)
					.name(appNAme)
					.serviceId(appNAme)
					.deregisterCriticalServiceAfter(Consul.deregisterInterval)
					.interval(Consul.healthCheckInterval)
					.script(script_check_to_consul+" "+"http://"+app_noeud+":"+app_port+app_check_uri)
					.build();
					
				agentClient.registerCheck(check);
```
As you can see, you API accept only one script parameter. So how your code split one String into an array ?
And this code produce the error :  
```
6:38:08,794 ERROR [stderr] (default task-15) com.orbitz.consul.ConsulException: Consul request failed with status [400]: Invalid check: TTL must be > 0 for TTL checks
16:38:08,795 ERROR [stderr] (default task-15) 	at com.orbitz.consul.util.Http.ensureResponseSuccessful(Http.java:59)
```

Please, let me know how make a simple check register with args (a script) and not a ttl check.

**Comment by sliabat** [comment]
official API : https://www.consul.io/api/agent/check.html

**Comment by yfouquet** [comment]
hi @sliabat,
The code does not split a string for script into an array; the usage of `Args` was not added and we were still based on single string `Script`.
I pushed a fix that should meet your needs.
