### ISSUE TITLE
ServiceHealthCache listener not triggered when service's health check turns passing

### ISSUE THREAD

**Issue by dennanisny** [rickfast/consul-client#342]
I have a service that takes about 2 minutes to start up, and the TCP health check (viewed from Consul Web UI) remains critical during the start-up period and turns green when the start-up completes.
My use case is that I need to perform some task both when the service's health check turns critical and passing.
My services are running as Docker containers and they are added/removed from Consul automatically by the Registrator.
When I start the service, the ServiceHealthCache's listener is triggered immediately after Registrator adds the service to the Consul, while the service's TCP check is still critical from Consul Web UI. However when the TCP check turns to passing, the listener is _not_ triggered.

Below is my relevant code snippet. Appreciate if anyone could help to clarify this.
```
ServiceHealthCache serviceHealthCache = ServiceHealthCache.newCache(
                        healthClient,
                        SERVICE_NAME,
                        true,
                        5,
                        ImmutableQueryOptions.builder().addTag("test").build());
serviceHealthCache.addListener(newValues -> doSomething());
serviceHealthCache.start();
```

**Comment by yfouquet** [comment]
Hi @dennanisny,

I've tryed to reproduce your issue and i got that:
- the listener is trigger "immediately" on cache startup; with no value as Consul returns an empty result. This is expected as it is not an error.
- the listener is called after every service status change.

Is the "test" tag added to all your services in Consul? Can you ensure that calling `http://<consul_host>:<consul_port>/v1/health/service/SERVICE_NAME?passing=true` returns your endpoints?
Can you please also tell us which version of Consul, and which version of the consul-client do you use?

**Comment by dennanisny** [comment]
Hi @yfouquet ,

Thanks for your quick response!
I'm using Consul 1.2.0 and consul-client 1.2.1.
Calling the url you provided did return my endpoints as expected.
However I noticed that for each service there is an additional Check as below besides the TCP check I specified.
Could it be due to the fact that this check was passing, the listener was triggered?
If that is the case, is there a way to instruct the cache to listen to a certain check?
```
{
"Node": "dev0006.internal.moqi.ai",
"CheckID": "serfHealth",
"Name": "Serf Health Status",
"Status": "passing",
"Notes": "",
"Output": "Agent alive and reachable",
"ServiceID": "",
"ServiceName": "",
"ServiceTags": [],
"Definition": {},
"CreateIndex": 63036,
"ModifyIndex": 63036
}
```

**Comment by yfouquet** [comment]
This check is the consul agent check. It is present for every service.
You should not worry about it as a service is passing only if all checks are passing.

Thanks for sharing the checks.
One more question: when you said that the listener was notified at startup, are your services sent to the listener? or is it empty notification?

**Comment by dennanisny** [comment]
I just checked that when the listener is notified at startup, the new service (with its health check still failing) is sent to the listener.

**Comment by yfouquet** [comment]
I know understand that you are notified with unhealthy service; am i correct?
Can you send the checks when your service is starting (not yet passing) so that i can reproduce the issue (using a mock agent).

**Comment by dennanisny** [comment]
That's correct.
Is this the "checks" your were referring to?
```
"Checks": [
            {
                "Node": "dev0006.internal.moqi.ai",
                "CheckID": "serfHealth",
                "Name": "Serf Health Status",
                "Status": "passing",
                "Notes": "",
                "Output": "Agent alive and reachable",
                "ServiceID": "",
                "ServiceName": "",
                "ServiceTags": [],
                "Definition": {},
                "CreateIndex": 63036,
                "ModifyIndex": 63036
            },
            {
                "Node": "dev0006.internal.moqi.ai",
                "CheckID": "service:dev0006.internal.moqi.ai:haiyangy_debug_matching-server-1_1:8208",
                "Name": "Service 'matching-server' check",
                "Status": "critical",
                "Notes": "",
                "Output": "dial tcp 10.1.1.16:33087: connect: connection refused",
                "ServiceID": "dev0006.internal.moqi.ai:haiyangy_debug_matching-server-1_1:8208",
                "ServiceName": "matching-server",
                "ServiceTags": [
                    "test"
                ],
                "Definition": {},
                "CreateIndex": 232039,
                "ModifyIndex": 232041
            }
        ]
```

**Comment by dennanisny** [comment]
I would like to add some more findings.
For each service, the listener is notified twice: first when the service is added (and unhealthy), then when the critical check turned passing.
Hope this helps.

**Comment by yfouquet** [comment]
I am using the following listener:
```
serviceHealthCache.addListener(newValues -> {
    System.out.println(String.format("Notification: %d [%s]",
        newValues.size(),
        newValues.values().stream().map(service -> service.getService().getId()).collect(Collectors.joining(","))));
});
```
And i get the following result:
```
Notification: 0 []
...
Notification: 1 [service:1]
```

I get a notification with no endpoints at startup (when `critical`), then 1 endpoint (when switch to `passing`). I get the same result with a mock using your checks.

**Comment by dennanisny** [comment]
Sorry that I just realized this is because I added `SERVICE_CHECK_INITIAL_STATUS: "passing"` as environment variable to the service's container definition, which forces the check to be passing on startup.
Apologies for the false alarm and thanks again for all the checking and advice!
