### ISSUE TITLE
Example 4 "Blocking call for value" not blocking

### ISSUE THREAD

**Issue by ixe013** [rickfast/consul-client#343]
I can't make the [blocking read code example to work](https://github.com/rickfast/consul-client#example-4-blocking-call-for-value). 

I was expecting this call to block, but it does not:
```
kvClient.getValue("foo", QueryOptions.blockMinutes(5, new BigInteger("0")).build(), callback);
````

If I do a long `Thread.sleep` after that call and change the watched value in Consul, `onComplete` will be called with the modified value. Using wireshark, I see the request go out as expected, with the one with the index not returning until the value is changed.
```
PUT http://localhost:8500/v1/kv/foo
GET http://localhost:8500/v1/kv/foo?wait=5m&index=0
GET http://localhost:8500/v1/kv/foo?wait=5m&index=79651

```
Did I miss something or must I add synchronization primitives (`wait`/`notify`) to that example to actually block waiting for a value change in Consul?

**Comment by yfouquet** [comment]
Hi @ixe013,

I think that i understand your concern.
This piece of code is an infinite loop that calls the local Consul agent constantly to get the up-to-date value for the `foo` key.
However, as you found out, it is supposed to run in a dedicated thread, or something similar.
If you just run this piece of code, it will terminate before the call of the callback.
You could add any synchronisation mechanism but it is supposed to not terminate, as after every Consul response a new request is emitted. This code is, for example, used in the caches. It runs in a separate thread until you call `close()` or terminate the process.
Am i answering your question?

We plan to have a look at the documentation but if you feel like you could make it clearer, please feel free to push a review.

**Comment by ixe013** [comment]
Thanks, it answers my question. The idea is that when `onComplete` read a new value, it would update a cache that would always hold the latest value for a given key in near real time. My use case is really to block the current thread until a value is written to a key (or until timeout is reached).

For the record, I have added `notify` to `onComplete`, something like this

```LOGGER.info("recursive wait returned");
if (value.getValueAsString().get().equals("placeholder")) {
   LOGGER.info("Watching some more");
   watch();
} else {
   LOGGER.info("Signaling that we got {}", value.getValueAsString().get());
   synchronized (signal) {
      signal.notify();
   }
}
```

And further down, on the same thread, do a `signal.wait(timeout)`.
