### ISSUE TITLE
How do I mock the Consul client call ?

### ISSUE THREAD

**Issue by agoncal** [rickfast/consul-client#352]
Hi,

I use the consul-client API to register services within Consul. The code looks like this (simplified version) : 

```
@Singleton
@Startup
public class ConsulManagementService {

    private Consul consul;
    private AgentClient agentClient;

    @PostConstruct
    protected void registerService() {

        consul = Consul.builder().withUrl(consulHost + ":" + consulPort).build();
        agentClient = consul.agentClient();

        final ImmutableRegistration registration =
            ImmutableRegistration.builder()
                                 .id(UUID.randomUUID().toString())
                                 .name(NUMBER_API_NAME)
                                 .address(numberApiHost)
                                 .port(numberApiPort)
                                 .check(http(numberApiHost + ":" + numberApiPort + "/number-api/api/numbers/health", 5))
                                 .build();
        agentClient.register(registration);
    }
}
```

This class being triggered at Startup, I need to mock the registration to Consul... but I don't know how to do it with Mockito. I've tried several things like : 

```
public class NumberResourceTest {

    private static Consul consulMock;
    private static AgentClient agentClientMock;


    @BeforeClass
    public static void setup() throws Exception {
        consulMock = mock(Consul.class);
        agentClientMock = mock(AgentClient.class);
        Consul.Builder consulBuilderMock = mock(Consul.Builder.class);
        when(consulBuilderMock.build()).thenReturn(consulMock);
        when(consulMock.agentClient()).thenReturn(agentClientMock);
    }
```

But I always get an exception because the `AgentClient` is trying to ping Consul:

```
Caused by: com.orbitz.consul.ConsulException: Error connecting to Consul
	at com.orbitz.consul.AgentClient.ping(AgentClient.java:67)
	at com.orbitz.consul.Consul$Builder.build(Consul.java:617)
	at org.bookstore.number.rest.ConsulManagementService.registerService(ConsulManagementService.java:69)
```

Any idea on how to mock the call to Consul ?

Thanks

**Comment by yfouquet** [comment]
Hi @agoncal,

In the example, your are creating a mock of the Consul builder `consulBuilderMock` which will return the mock of Consul `consulMock`, etc. However, `consulBuilderMock` is not used as `Consul.builder()` will not use your builder.
There are two ways to actually to it:
1. Mock the static call to `Consul.builder()` using Powermock for instance. But i would not recommend that.
2. Inject a instance of `Consul` in `ConsulManagementService` using `@autowired` of something similar. That way, you can override it during your tests.

Let us know if you succeed or have more questions.

**Comment by agoncal** [comment]
But if `Consul` is created buy the `Builder`, shouldn't the `Builder` be the one being injected (except that it's a static class and it can't using CDI and `@Inject`) ?

**Comment by yfouquet** [comment]
Yes, you can also inject the builder. I'm not familiar with the framework but i don't see any problem to inject it.

**Comment by getjack** [comment]
@agoncal This piece of code works for me without injection.

```
final Consul consulMock = mock(Consul.class);
// ... Mock all the method calls here

// Mock Consul.Builder
final Consul.Builder consulBuilderMock = mock(Consul.Builder.class);
when(consulBuilderMock.withUrl(anyString())).thenReturn(consulBuilderMock);
when(consulBuilderMock.build()).thenReturn(consulMock);

final MockedStatic<Consul> consulMockedStatic = mockStatic(Consul.class);
consulMockedStatic.when(Consul::builder).thenReturn(consulBuilderMock);
```

Be sure to use the mockito-inline depedency (for now)
