### ISSUE TITLE
All the keys are called in listener when value of only 1 of the key changes

### ISSUE THREAD

**Issue by abhayJava** [rickfast/consul-client#361]
if there are 3 keys k1,k2,k3 in /dummy/ folder in consul. If value of one of the key changes then in newValues.keySet() gives list of all the 3 keys. Ideally the set should contain only k1.

 
cache.addListener(newValues -> {
				Set<String> keys = newValues.keySet();
}

Is there any way to configure so that I receive only k1

**Comment by rickfast** [comment]
unfortunately, consul doesn't tell clients what key changed when performing a watch. your best bet is to do a comparison with the previous set of values.

from the Consul website:

> The "keyprefix" watch type is used to watch a prefix of keys in the KV store. It requires that the "prefix" parameter be specified. This watch returns all keys matching the prefix whenever any key matching the prefix changes.

**Comment by San-Troy** [comment]
Will this project support "key" watch type rather than only "keyprefix" in the future? So that specific keys can be watched separately even if they hava a common prefix.

I noticed that parameter "recurse" in url is always set to "true". May it help if make "recurse" be optional ?
