### ISSUE TITLE
Regex support for KV Cache

### ISSUE THREAD

**Issue by reivvax** [rickfast/consul-client#373]
Hello,
Is the newCache() method supports regex as the rootpath parameter ?
Giving the following code :

`final KeyValueClient kvClient = this.consul.keyValueClient();`
`final KVCache cache = KVCache.newCache(kvClient, "env\/.*\/folder\/");`

Would the cache be listening to the following path for example : env/6546518/folder/ ?

**Comment by rickfast** [comment]
This is more of a Consul question than a question about this client. I doubt that Consul supports this use case, and this client simply wraps the Consul APIs

**Comment by reivvax** [comment]
Thanks for the answer.

Yes indeed, Consul API does not look to support this use case.
