### ISSUE TITLE
version 1.3.3 released on maven central, but no release here?

### ISSUE THREAD

**Issue by Crim** [rickfast/consul-client#379]
Looks like 1.3.3 is on [maven central](https://mvnrepository.com/artifact/com.orbitz.consul/consul-client/1.3.3) but nothing in this github project?

**Comment by rickfast** [comment]
the tagging got messed up. the last 1.3.2 is actually 1.3.3

**Comment by Crim** [comment]
Got it, just making sure something nefarious hadn't happened :)
