### ISSUE TITLE
Can you please provide support to pass X-Consul-Token in header

### ISSUE THREAD

**Issue by bdhayakar** [rickfast/consul-client#383]
Hi,

Does the library support passing "X-Consul-Token" in headers.
As per consul documentation https://www.consul.io/api/index.html, passing token as query parameter is discouraged.
Is there any plan to implement this feature.

Thanks
Dayakar

**Comment by rickfast** [comment]
fixed by #384

**Comment by bdhayakar** [comment]
@rickfast , Thanks for the update.
